import os
from pathlib import Path
from datetime import timedelta, timezone

# ── Config ──────────────────────────────────────────────────────────
VAULT = os.environ.get("OBSIDIAN_VAULT_PATH", str(Path.home() / "vault"))
MEETINGS_DIR = Path(VAULT) / "Meetings"
TASKS_DIR = Path(VAULT) / "Tasks"
TASKS_ARCHIVE_DIR = TASKS_DIR / "Archive"
ARTIFACTS_DIR = MEETINGS_DIR / ".meetcap"

BRT = timezone(timedelta(hours=-3))

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_KEY = os.environ.get("OPENROUTER_API_KEY", "")
LLM_MODEL = os.environ.get("MEETCAP_LLM_MODEL", "qwen/qwen3.7-flash")

SUMMARY_MAX_TOKENS = 4096
TASK_SUGGESTIONS_MAX_TOKENS = 3000
SUMMARY_TEMPERATURE = 0.3
TASK_SUGGESTIONS_TEMPERATURE = 0.0

SUMMARY_SINGLE_PASS_MAX_CHARS = 15000
SUMMARY_CHUNK_MAX_CHARS = 30000
SUMMARY_MERGE_MAX_CHARS = 22000
TASK_SUGGESTIONS_TRANSCRIPT_MAX_CHARS = 10000
TASK_TRANSCRIPT_MAX_CHARS = 10000

CLAIMS_MAX_TOKENS = 2500
CLAIMS_TEMPERATURE = 0.0
CLAIMS_MIN = 3
CLAIMS_MAX = 5
CLAIMS_TRANSCRIPT_MAX_CHARS = 30000
CLAIMS_QUOTE_HEAD_WORDS = 8
CLAIMS_MAX_TIMESTAMPS = 3

ENTITY_HIGH_CONFIDENCE = 0.87
ENTITY_MEDIUM_CONFIDENCE = 0.75

QA_MAX_TOKENS = 3200
QA_TEMPERATURE = 0.0
QA_TRANSCRIPT_MAX_CHARS = 24000
QA_NOTE_MAX_CHARS = 8000
QA_COVERAGE_THRESHOLD = 0.75
QA_MAX_ITEMS = 5

MANIFEST_MAX_TOKENS = 2000
MANIFEST_TEMPERATURE = 0.0
MANIFEST_TRANSCRIPT_MAX_CHARS = 16000
MANIFEST_MAX_ITEMS = 6

EXPORT_QA_ENABLED = os.environ.get("MEETCAP_EXPORT_QA", "1") != "0"
EXPORT_MANIFEST_ENABLED = os.environ.get("MEETCAP_EXPORT_MANIFEST", "1") != "0"
